// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sounding_default
Rcpp::NumericVector sounding_default(Rcpp::NumericVector pressure, Rcpp::NumericVector altitude, Rcpp::NumericVector temp, Rcpp::NumericVector dpt, Rcpp::NumericVector wd, Rcpp::NumericVector ws, Rcpp::NumericVector export_profile, Rcpp::NumericVector accuracy);
RcppExport SEXP _thunder_sounding_default(SEXP pressureSEXP, SEXP altitudeSEXP, SEXP tempSEXP, SEXP dptSEXP, SEXP wdSEXP, SEXP wsSEXP, SEXP export_profileSEXP, SEXP accuracySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pressure(pressureSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type altitude(altitudeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type temp(tempSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dpt(dptSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type wd(wdSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ws(wsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type export_profile(export_profileSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type accuracy(accuracySEXP);
    rcpp_result_gen = Rcpp::wrap(sounding_default(pressure, altitude, temp, dpt, wd, ws, export_profile, accuracy));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_thunder_sounding_default", (DL_FUNC) &_thunder_sounding_default, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_thunder(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
