// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sounding_default
Rcpp::NumericVector sounding_default(Rcpp::NumericVector pressure, Rcpp::NumericVector altitude, Rcpp::NumericVector temperature, Rcpp::NumericVector dew, Rcpp::NumericVector angle, Rcpp::NumericVector velocity, Rcpp::NumericVector export_profile, Rcpp::NumericVector accuracy);
RcppExport SEXP _thunder_sounding_default(SEXP pressureSEXP, SEXP altitudeSEXP, SEXP temperatureSEXP, SEXP dewSEXP, SEXP angleSEXP, SEXP velocitySEXP, SEXP export_profileSEXP, SEXP accuracySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pressure(pressureSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type altitude(altitudeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type temperature(temperatureSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dew(dewSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type angle(angleSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type velocity(velocitySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type export_profile(export_profileSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type accuracy(accuracySEXP);
    rcpp_result_gen = Rcpp::wrap(sounding_default(pressure, altitude, temperature, dew, angle, velocity, export_profile, accuracy));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_thunder_sounding_default", (DL_FUNC) &_thunder_sounding_default, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_thunder(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
