# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generic function for calculating thermo- and kinematic indices derived from atmospheric profiling.
#' 
#' 
#'
#' @param pressure pressure [hPa]
#' @param altitude altitude [meters above surface]
#' @param temperature air temperature [degree Celsius]
#' @param dew dew point temperature [degree Celsius]
#' @param angle wind direction [degrees]
#' @param velocity wind speed [metres per second]
#' @param export_profile runtime parameters
#' @examples 
#' pressure <- c(1000, 855, 700, 500, 300, 100, 10)
#' altitude <- c(0, 1500, 2500, 6000, 8500, 12000, 25000)
#' temp <- c(25, 10, 0, -15, -30, -50, -92)
#' dpt <- c(20, 5, -5, -30, -55, -80, -99)
#' wd <- c(0, 90, 135, 180, 270, 350, 0)
#' ws <- c(5, 10, 20, 30, 40, 5, 0)
#' sounding(pressure, altitude, temp, dpt, wd, ws)
#' @useDynLib thunder
#' @importFrom Rcpp evalCpp
#' @export
sounding_default <- function(pressure, altitude, temperature, dew, angle, velocity, export_profile, accuracy) {
    .Call('_thunder_sounding_default', PACKAGE = 'thunder', pressure, altitude, temperature, dew, angle, velocity, export_profile, accuracy)
}

