# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generic function for calculating convective parameters commonly used in the operational prediction of severe convective storms.
#' Further details are provided in the sounding_compute() function
#' 
#'
#' @param pressure - pressure [hPa]
#' @param altitude - altitude [meters]
#' @param temp - temperature [degree Celsius]
#' @param dpt - dew point temperature [degree Celsius]
#' @param wd - wind direction [azimuth in degrees]
#' @param ws - wind speed [kn]
#' @param export_profile - possibility to export interpolated profile on the levels defined in accuracy configuration
#' @param accuracy - accuracy of computations where 3 = high (slow), 2 = medium (recommended), 1 = low (fast)
#' @examples 
#' pressure <- c(1000, 855, 700, 500, 300, 100, 10) 
#' altitude <- c(0, 1500, 2500, 6000, 8500, 12000, 25000)
#' temp <- c(25, 10, 0, -15, -30, -50, -92)
#' dpt <- c(20, 5, -5, -30, -55, -80, -99)
#' wd <- c(0, 90, 135, 180, 270, 350, 0)
#' ws <- c(5, 10, 20, 30, 40, 5, 0)
#' accuracy <- 2 
#' export_profile <- 0
#' sounding_compute(pressure, altitude, temp, dpt, wd, ws, export_profile, accuracy)
#' @useDynLib thunder
#' @importFrom Rcpp evalCpp
#' @export
sounding_default <- function(pressure, altitude, temp, dpt, wd, ws, export_profile, accuracy) {
    .Call('_thunder_sounding_default', PACKAGE = 'thunder', pressure, altitude, temp, dpt, wd, ws, export_profile, accuracy)
}

